# LOAD LOCAL CONFIGURATION
if File.exists?("#{Rails.root}/config/local.yml")
  APP_CONFIG = YAML.load_file("#{Rails.root}/config/local.yml")[Rails.env]
end
APP_CONFIG ||= {}

# FROM HEROKU.YML
PRODUCT_CLASS_NAME =    ENV['PRODUCT_CLASS_NAME']     || APP_CONFIG['PRODUCT_CLASS_NAME']
SITE_URL =              ENV['SITE_URL']               || APP_CONFIG['SITE_URL']
# CDN
S3_ACCESS_KEY_ID =      ENV['S3_ACCESS_KEY_ID']       || APP_CONFIG['S3_ACCESS_KEY_ID']
S3_SECRET_ACCESS_KEY =  ENV['S3_SECRET_ACCESS_KEY']   || APP_CONFIG['S3_SECRET_ACCESS_KEY']
S3_BUCKET =             ENV['S3_BUCKET']              || APP_CONFIG['S3_BUCKET']
# Social Networks
FB_APP_ID =             ENV['FB_APP_ID']              || APP_CONFIG['FB_APP_ID']
FB_APP_SECRET =         ENV['FB_APP_SECRET']          || APP_CONFIG['FB_APP_SECRET']
TW_APP_ID =             ENV['TW_APP_ID']              || APP_CONFIG['TW_APP_ID']
TW_APP_SECRET =         ENV['TW_APP_SECRET']          || APP_CONFIG['TW_APP_SECRET']
# Security
SECRET_TOKEN =          ENV['SECRET_TOKEN']           || APP_CONFIG['SECRET_TOKEN']
COOKIE_STORE_KEY =      ENV['COOKIE_STORE_KEY']       || APP_CONFIG['COOKIE_STORE_KEY']
# External Services
RECAPTCHA_PUB_KEY =     ENV['RECAPTCHA_PUB_KEY']      || APP_CONFIG['RECAPTCHA_PUB_KEY']
RECAPTCHA_PVT_KEY =     ENV['RECAPTCHA_PVT_KEY']      || APP_CONFIG['RECAPTCHA_PVT_KEY']
RAKISMET_KEY =          ENV['RAKISMET_KEY']           || APP_CONFIG['RAKISMET_KEY']
RAKISMET_URL =          ENV['RAKISMET_URL']           || APP_CONFIG['RAKISMET_URL']
# Paypal
PAYPAL_ACCOUNT =        ENV['PAYPAL_ACCOUNT']         || APP_CONFIG['PAYPAL_ACCOUNT']
PAYPAL_MODE =           ENV['PAYPAL_MODE']            || APP_CONFIG['PAYPAL_MODE']
PAYPAL_API_USERNAME =   ENV['PAYPAL_API_USERNAME']    || APP_CONFIG['PAYPAL_API_USERNAME']
PAYPAL_API_PASS =       ENV['PAYPAL_API_PASS']        || APP_CONFIG['PAYPAL_API_PASS']
PAYPAL_API_SIGN =       ENV['PAYPAL_API_SIGN']        || APP_CONFIG['PAYPAL_API_SIGN']

# THIS ONES ARE NOT IN HEROKU.YML OR LOCAL.YML
MAILER_SENDER =         ENV['MAILER_SENDER']          || APP_CONFIG['MAILER_SENDER']
PEPPER_TOKEN =          ENV['PEPPER_TOKEN']           || APP_CONFIG['PEPPER_TOKEN']
SUPPORT_EMAIL =         ENV['SUPPORT_EMAIL']          || APP_CONFIG['SUPPORT_EMAIL']
MAIL_BCC =              ENV['MAIL_BCC']               || APP_CONFIG['MAIL_BCC']
SITE_NAME =             ENV['SITE_NAME']              || APP_CONFIG['SITE_NAME']
SITE_TAGLINE =          ENV['SITE_TAGLINE']           || APP_CONFIG['SITE_TAGLINE']
SITE_DOMAIN =           ENV['SITE_DOMAIN']            || APP_CONFIG['SITE_DOMAIN']
GAE_TRACKING_CODE =     ''
STATIC_ASSETS_PATH = 	  ''
CUSTOM_META =           ''
META_DESCRIPTION =      ''
META_KEYWORDS =         ''
HEAD_TAG =              ''
AFTER_BODY_TAG_START =  ''
BEFORE_BODY_TAG_END =   ''
