#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: squarestays
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT: "development:test"
    S3_ACCESS_KEY_ID: 
    S3_SECRET_ACCESS_KEY: 
    S3_BUCKET: squarestays-img-production
    FB_APP_ID: 
    FB_APP_SECRET: 
    TW_APP_ID: 
    TW_APP_SECRET: 
    BACKEND_PATH: https://squarestays-backend.heroku.com
    SECRET_TOKEN: b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY: _SquareStaysProductionFrontEnd_session

staging:
  app: frontend-heypal
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT: "development:test"
    S3_ACCESS_KEY_ID: 
    S3_SECRET_ACCESS_KEY: 
    S3_BUCKET: squarestays-img-staging
    FB_APP_ID: 
    FB_APP_SECRET: 
    TW_APP_ID: 
    TW_APP_SECRET: 
    BACKEND_PATH: https://backend-heypal.heroku.com
    SECRET_TOKEN: b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY: _SquareStaysStagingFrontEnd_session
